### ISSUE TITLE
Placeholder for Recipe Reading as 'null'

### ISSUE THREAD

**Issue by DemarcoFC** [BreweryTeam/BreweryRecipesAddon#5]
When redeeming a recipe, the chat reads:

"You have learned the 'null' recipe!" instead of the actual name of the recipe.

**Comment by Jsinco** [comment]
Could be a result of not having a messages section in your Recipes config. Double check and make sure you have this:

```yml
messages:
  already-learned: 'You already know this recipe!'
  learned: 'You have learned the ''%s'' recipe&r!'
```
